# Generated by Django 5.1 on 2025-05-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='category',
            field=models.CharField(choices=[('telephone', 'Telephone'), ('ordinateur', 'Ordinateur'), ('accessoire', 'Accessoire'), ('ecran', 'Ecran'), ('imprimante', 'Imprimante'), ('tablette', 'Tablette'), ('casque', 'Casque'), ('clavier', 'Clavier'), ('souris', 'Souris'), ('modem', 'Modem'), ('disquedur', 'Disque dur'), ('cleusb', 'Cle USB'), ('autre', 'Autre')], default='ordinateur', max_length=20),
        ),
        migrations.AddField(
            model_name='produit',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
