# Generated by Django 5.1 on 2025-05-18 02:28

import django.utils.timezone
from django.db import migrations, models


def convertir_boutique_en_boolean(apps, schema_editor):
    # Obtenir le modèle avec le champ boutique
    Partenaire = apps.get_model('core', 'Partenaire')
    # Convertir les valeurs existantes
    for partenaire in Partenaire.objects.all():
        # Si boutique > 0, alors True, sinon False
        partenaire.boutique = bool(partenaire.boutique)
        partenaire.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produit_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partenaire',
            name='type',
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='nom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='prenom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='telephone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='facture',
            name='nom',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='facture',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='dateadhesion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='localisation',
            field=models.CharField(default='Bafoussam', max_length=100),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='prenom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='statut',
            field=models.CharField(choices=[('encours', 'En Cours'), ('paye', 'Payé')], default='encours', max_length=20),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='telephone',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix_achat',
            field=models.FloatField(blank=True, default=0),
        ),
        # Exécuter d'abord une fonction Python pour convertir les données
        migrations.RunPython(convertir_boutique_en_boolean),
        # Ensuite modifier le type de champ
        migrations.AlterField(
            model_name='partenaire',
            name='boutique',
            field=models.BooleanField(default=True),
        ),
    ]