# Generated by Django 5.1 on 2025-05-08 19:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_produit_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partenaire',
            name='type',
        ),
        migrations.AddField(
            model_name='partenaire',
            name='dateadhesion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='localisation',
            field=models.CharField(default='Bafoussam', max_length=100),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='prenom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='statut',
            field=models.CharField(choices=[('encours', 'En Cours'), ('paye', 'Payé')], default='encours', max_length=20),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='telephone',
            field=models.CharField(default=0, max_length=20),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='boutique',
            field=models.BooleanField(default=True),
        ),
    ]
