# Generated by Django 5.1 on 2025-05-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_partenaire_type_partenaire_dateadhesion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commandeclient',
            name='nom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='prenom',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='commandeclient',
            name='telephone',
            field=models.CharField(default='', max_length=100),
        ),
    ]
