# Generated by Django 5.1 on 2025-05-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_commandeclient_nom_commandeclient_prenom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='nom',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
