# Generated by Django 5.1 on 2025-05-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_facture_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
