# Generated by Django 5.1 on 2025-05-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_facture_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='prix_achat',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
