# Generated by Django 5.1 on 2025-05-18 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_produit_prix_achat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partenaire',
            name='boutique',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='telephone',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
